site_name: SMT Knowledge Base
site_url: https://geos-esm.github.io/SMT-Nebulae/
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - search.share
nav:
  - Home: index.md
  - Project 2426:
    - Overview: project2426/index.md
    - Milestone 1: project2426/milestone1.md
    - Milestone 2: project2426/milestone2.md
    - Milestone 3: project2426/milestone3.md
    - Milestone 4: project2426/milestone4.md
    - Results:
      - Milestone 2: project2426/results/M2_Sept25/summary.md
      - Supercomputing 23: project2426/results/SC23.md
      - Science Targets: project2426/results/science-targets.md
      - HPC Metrics: project2426/results/hpc-metrics.md
  - Technical:
    - Overview: technical/index.md
    - The Laundry List 👕: technical/laundry-list.md
    - Dev setup:
      - Overview: technical/dev-setup/index.md
      - Tech stack: technical/dev-setup/tech-stack.md
      - VSCode config: technical/dev-setup/vscode.md
    - Frontend:
      - Overview: technical/frontend/index.md
      - NDSL features: technical/frontend/ndsl_features.md
      - Experimental "physics" features: technical/frontend/experimental_features.md
      - ADRs:
        - Index: technical/frontend/ADRs/index.md
        - Fields Bundle: technical/frontend/ADRs/fields_bundle.md
    - Porting:
      - Translate tests: technical/porting/translate_test.md
    - Backend work:
      - Overview: technical/backend/index.md
      - Schedule Tree bridge: technical/backend/schedule-tree.md
      - Coding guidelines: technical/backend/coding-guidelines.md
      - Orchestration: technical/backend/orchestration.md
      - Repositories:
        - NDSL: technical/backend/repositories/ndsl.md
        - GT4Py: technical/backend/repositories/gt4py.md
        - DaCe: technical/backend/repositories/dace.md
      - ADRs:
        - Index: technical/backend/ADRs/index.md
        - Schedule tree: technical/backend/ADRs/stree.md
        - Schedule tree (DaCe version): technical/backend/ADRs/stree_dace-version.md
        - Schedule tree (NDSL integration): technical/backend/ADRs/stree_ndsl-integration.md
      - Archive:
        - GT4Py/DaCe bridge via expansion: technical/backend/dace-bridge.md
  - GEOS:
    - Overview: GEOS/index.md
    - Local build: GEOS/local_build.md
    - Discover: GEOS/discover_build.md
    - PRISM (GH200): GEOS/gh200.md
    - Validation: GEOS/validation_basics.md
    - Component documentation:
      - Overview: GEOS/components/index.md
      - Dynamics:
        - pyFV3: GEOS/components/dynamics/pyFV3.md
      - Moist:
        - Overview: GEOS/components/moist/index.md
        - GF: GEOS/components/moist/GF.md
        - GFDL_1M: GEOS/components/moist/GFDL_1M.md
        - RAS: GEOS/components/moist/RAS.md
        - UW: GEOS/components/moist/UW.md
  - Tutorials:
    - Start Here!: tutorials/index.md
    - NDSL:
      - 1. Introduction to NDSL: tutorials/ndsl_user_manual/ndsl_introduction.md
      - 2. Data Types and Storage: tutorials/ndsl_user_manual/data.md
      - 3. Writing Code with NDSL: tutorials/ndsl_user_manual/writing_ndsl_code.md
      - 4. Advanced Features: tutorials/ndsl_user_manual/advanced_features.md
      - 5. Backends: tutorials/ndsl_user_manual/backends.md
      - 6. Common Patterns: tutorials/ndsl_user_manual/common_patterns.md
      - 7. Why Use Classes?: tutorials/ndsl_user_manual/why_use_classes.md
      - 8. Best Coding Practices: tutorials/ndsl_user_manual/best_coding_practices.md
    - GEOS:
      - Introduction to GEOS: tutorials/geos_with_ndsl/index.md
    - Model Development with NDSL:
      - Model Development with NDSL: tutorials/developing_with_ndsl/index.md
    - FAQ: tutorials/faq.md

  - The Code Nebula:
    - Overview: tcn/index.md
    - Packages: tcn/packages.md
    - Results: tcn/results.md
  - Satellite work:
    - Pace: satellite-work/pace.md
markdown_extensions:
  # simple glossary file
  - abbr
  # support for colored notes / warnings / tips / examples
  - admonition
  # emoji support
  - attr_list
  # support for definition lists (e.g. FAQ)
  - def_list
  # support for footnotes
  - footnotes
  # supercharges admonitions by making them collapsible
  - pymdownx.details
  # support for emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # support for syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        # hover tooltips for abbreviations (simple glossary)
        - ./includes/glossary.md
  - pymdownx.superfences:
      custom_fences:
      # support for mermaid graphs
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  # support for task list of the form `- [ ] task name`
  - pymdownx.tasklist:
      custom_checkbox: false
plugins:
  # use drawio diagrams as if they were images
  - drawio
  # add search box to the header, configuration in theme
  - search
extra_css:
  - stylesheets/extra.css
watch:
  # reload when the glossary file is updated
  - includes
