site_name: SMT Knowledge Base
site_url: https://geos-esm.github.io/SMT-Nebulae/
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - search.share
nav:
  - Home: index.md
  - Project 2426:
    - Overview: project2426/index.md
    - Milestone 1: project2426/milestone1.md
    - Milestone 2: project2426/milestone2.md
    - Milestone 3: project2426/milestone3.md
    - Milestone 4: project2426/milestone4.md
    - Results:
      - Milestone 2: project2426/results/M2.md
      - Supercomputing 23: project2426/results/SC23.md
      - Science Targets: project2426/results/science-targets.md
      - HPC Metrics: project2426/results/hpc-metrics.md
  - Technical:
    - Dev setup:
      - Tech stack: technical/dev-setup/tech-stack.md
      - VSCode config: technical/dev-setup/vscode.md
    - Frontend:
      - Experimental "physics" features: technical/frontend/experimental_features.md
    - Porting:
      - Translate tests: technical/porting/translate_test.md
    - Backend work:
      - Overview: technical/backend/index.md
      - GT4Py/DaCe bridge: technical/backend/dace-bridge.md
      - Coding guidelines: technical/backend/coding-guidelines.md
      - Repositories:
        - NDSL: technical/backend/repositories/ndsl.md
        - GT4Py: technical/backend/repositories/gt4py.md
        - DaCe: technical/backend/repositories/dace.md
  - GEOS:
    - Overview: GEOS/index.md
    - Local build: GEOS/local_build.md
    - Discover: GEOS/discover_build.md
    - Validation: GEOS/validation_basics.md
    - Component documentation:
      - Overview: GEOS/components/index.md
      - moist:
        - Overview: GEOS/components/moist/index.md
        - GF: GEOS/components/moist/GF.md
        - GFDL_1M: GEOS/components/moist/GFDL_1M.md
        - RAS: GEOS/components/moist/RAS.md
        - UW: GEOS/components/moist/UW.md
  - Tutorials:
    - Introduction: tutorials/index.md
    - NDSL:
      - Introduction to NDSL: tutorials/how_to_ndsl/ndsl_introduction.md
      - Data Types and Storage: tutorials/how_to_ndsl/data.md
      - Stencils and Functions: tutorials/how_to_ndsl/stencil_function_basics.md
      - Advanced Stencil Features: tutorials/how_to_ndsl/advanced_stencil_features.md
      - Common Patterns: tutorials/how_to_ndsl/common_patterns.md
      - Importance of Object Oriented Coding: tutorials/how_to_ndsl/why_use_classes.md
    - GEOS:
      - Introduction to GEOS: tutorials/geos_with_ndsl/index.md
    - Model Development with NDSL:
      - Model Development with NDSL: tutorials/developing_with_ndsl/index.md

  - The Code Nebula:
    - Overview: tcn/index.md
    - Packages: tcn/packages.md
    - Results: tcn/results.md
  - Satellite work:
    - Pace: satellite-work/pace.md
markdown_extensions:
  # simple glossary file
  - abbr
  # support for colored notes / warnings / tips / examples
  - admonition
  # emoji support
  - attr_list
  # support for footnotes
  - footnotes
  # supercharges admonitions by making them collapsible
  - pymdownx.details
  # support for emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # support for syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        # hover tooltips for abbreviations (simple glossary)
        - ./includes/glossary.md
  - pymdownx.superfences:
      custom_fences:
      # support for mermaid graphs
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  # use drawio diagrams as if they were images
  - drawio
  # add search box to the header, configuration in theme
  - search
watch:
  # reload when the glossary file is updated
  - includes
