site_name: SMT Knowledge Base
site_url: https://geos-esm.github.io/SMT-Nebulae/
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - search.share
nav:
  - Home: index.md
  - Project 2426:
    - Overview: project2426/index.md
    - Milestone 1: project2426/milestone1.md
    - Milestone 2: project2426/milestone2.md
    - Milestone 3: project2426/milestone3.md
    - Milestone 4: project2426/milestone4.md
    - Results:
      - Milestone 2: project2426/results/M2.md
      - Supercomputing 23: project2426/results/SC23.md
      - Science Targets: project2426/results/science-targets.md
      - HPC Metrics: project2426/results/hpc-metrics.md
  - Dev setup:
    - Tech stack: dev-setup/tech-stack.md
    - VSCode config: dev-setup/vscode.md
  - GEOS:
    - Overview: GEOS/index.md
    - Local build: GEOS/local_build.md
    - Discover: GEOS/discover_build.md
    - Validation: GEOS/validation_basics.md
    - Component documentation:
      - Overview: GEOS/components/index.md
      - moist:
        - Overview: GEOS/components/moist/index.md
        - GF: GEOS/components/moist/GF.md
        - GFDL_1M: GEOS/components/moist/GFDL_1M.md
        - RAS: GEOS/components/moist/RAS.md
        - UW: GEOS/components/moist/UW.md
  - Porting:
    - Translate tests: porting/translate_test.md
  - Backend work:
    - Overview: backend/index.md
    - GT4Py/DaCe bridge: backend/dace-bridge.md
    - Coding guidelines: backend/coding-guidelines.md
    - Repositories:
      - NDSL: backend/repositories/ndsl.md
      - GT4Py: backend/repositories/gt4py.md
      - DaCe: backend/repositories/dace.md
  - The Code Nebula:
    - Overview: tcn/index.md
    - Packages: tcn/packages.md
    - Results: tcn/results.md
  - Satellite work:
    - Pace: satellite-work/pace.md
markdown_extensions:
  # simple glossary file
  - abbr
  # support for colored notes / warnings / tips / examples
  - admonition
  # support for footnotes
  - footnotes
  # supercharges admonitions by making them collapsible
  - pymdownx.details
  # support for syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        # hover tooltips for abbreviations (simple glossary)
        - includes/glossary.md
  - pymdownx.superfences:
      custom_fences:
      # support for mermaid graphs
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  # use drawio diagrams as if they were images
  - drawio
  # add search box to the header, configuration in theme
  - search
watch:
  # reload when the glossary file is updated
  - includes
