# Discover's CI check

name: Discover Nightly GEOS Held-Suarez Validation

on:
  # On Hold pending revisit CI altogether
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '0 0 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  GEOS_Held-Suarez :
    uses: GEOS-ESM/CI-workflows/.github/workflows/geosongpu-ondemand.yml@project/geosongpu
    with:
      experiment_name:   geos_hs
      experiment_action: Validation
      geosongpu_ci_ref: ${{ github.ref_name }}
